### ISSUE TITLE
OT: precompiled DLLs

### ISSUE THREAD

**Issue by sivaramn** [zklhp/emacs-w64#2]
Hi,

Could you please tell me where you got the 64bit DLLs from?  Did you build them yourself or download them from somewhere?  I couldn't get the stock gnu emacs to view images and I couldn't find any 64 bit DLLs , was wondering where you got them from.
## 

Sivaram

**Comment by zklhp** [comment]
Hello Sivaramn,

These dlls are copied from `/mingw64/bin` with the following commmand:

```
cp /mingw64/bin/{libdbus-*.dll,libwinpthread-*.dll,libXpm-*.dll,libgomp-*.dll,libgcc_s_seh-*.dll,libglib-*.dll,libintl-*.dll,libiconv-*.dll,libgobject-*.dll,libffi-*.dll,libgdk_pixbuf-*.dll,libgio-*.dll,libgmodule-*.dll,zlib*.dll,librsvg-*.dll,libcairo-*.dll,libcroco-*.dll,libpango-*.dll,libpangocairo-*.dll,libxml2-*.dll,libfontconfig-*.dll,libfreetype-*.dll,libpixman-*.dll,libpng*.dll,libpangoft*.dll,libpangowin32-*.dll,liblzma-*.dll,libexpat-*.dll,libharfbuzz-*.dll,libgnutls-*.dll,libgnutlsxx-*.dll,libtiff-*.dll,libtiffxx-*.dll,libjpeg-*.dll,libgif-*.dll,libbz2-*.dll,libjbig-*.dll,libgmp-*.dll,libhogweed-*.dll,libnettle-*.dll,libp11-kit-*.dll,libtasn1-*.dll,libidn-*.dll,libpcre-*.dll,libgraphite*.dll,libstdc++-*.dll} /tmp/emacs/bin
```

And these dlls files are part of packages built by the msys2 project. If you don’t want them installed, you may get them from

http://repo.msys2.org/mingw/x86_64/

And the corresponding packages are:
- mingw-w64-x86_64-bzip2
- mingw-w64-x86_64-cairo
- mingw-w64-x86_64-dbus
- mingw-w64-x86_64-expat
- mingw-w64-x86_64-fontconfig
- mingw-w64-x86_64-freetype
- mingw-w64-x86_64-gcc-libs
- mingw-w64-x86_64-gdk-pixbuf2
- mingw-w64-x86_64-gettext
- mingw-w64-x86_64-giflib
- mingw-w64-x86_64-glib2
- mingw-w64-x86_64-gmp
- mingw-w64-x86_64-gnutls
- mingw-w64-x86_64-graphite2
- mingw-w64-x86_64-harfbuzz
- mingw-w64-x86_64-jbigkit
- mingw-w64-x86_64-libcroco
- mingw-w64-x86_64-libffi
- mingw-w64-x86_64-libiconv
- mingw-w64-x86_64-libidn
- mingw-w64-x86_64-libjpeg-turbo
- mingw-w64-x86_64-libpng
- mingw-w64-x86_64-librsvg
- mingw-w64-x86_64-libtasn1
- mingw-w64-x86_64-libtiff
- mingw-w64-x86_64-libwinpthread-git
- mingw-w64-x86_64-libxml2
- mingw-w64-x86_64-nettle
- mingw-w64-x86_64-p11-kit
- mingw-w64-x86_64-pango
- mingw-w64-x86_64-pcre
- mingw-w64-x86_64-pixman
- mingw-w64-x86_64-xpm-nox
- mingw-w64-x86_64-xz
- mingw-w64-x86_64-zlib

There seems to exist a script to fetch the files, but I don’t know whether it works.

Best regards,

Chris

**Comment by zklhp** [comment]
I am closing the issue. Please feel free to comment.
