### ISSUE TITLE
25.1 locks up when there are unicode characters

### ISSUE THREAD

**Issue by xvz** [zklhp/emacs-w64#4]
For all 3 versions of Emacs-w64 25.1, Emacs becomes very sluggish and eventually freezes when editing text with unicode characters. I've tested with -Q and in a clean VM to rule out my configs. Running on Win 7 x64.

To reproduce:
1. runemacs.exe -Q
2. Paste "★" into scratch buffer
3. Try to navigate around---cursor is sluggish. Eventually Emacs freezes, becomes unresponsive to C-g, and can only be killed.

This doesn't happen with emacs-bin-w64-24.5-1 and I've not encountered any issues with 25.1.1 on Ubuntu.

**Comment by zklhp** [comment]
Hi,
Sorry for that. Maybe it is [bug#24634](http://lists.gnu.org/archive/html/bug-gnu-emacs/2016-10/msg00334.html). What font are you using? You can find the information by put the cursor before “★” and `M-x describe-char`. For me, the font is Symbola (download form http://users.teilar.gr/~g1951d/), and I see no problem.

Sorry,
Chris

**Comment by zklhp** [comment]
Or could you please try the official version at https://ftp.gnu.org/gnu/emacs/windows/, and see whether the problem is present.

Thank you.

**Comment by xvz** [comment]
Oh good point. Same problem with the official version. describe-char output has "uniscribe:-outline-BatangChe-normal-normal-normal-mono-15-_-_-_-c-_-gb2312.1980-0 (#xB18)".

Thanks for the bug pointer, I had trouble finding a relevant bug. Does seem like a source issue. I'll stick with 24.5 for now.

**Comment by zklhp** [comment]
Hi,

This font is “buggy”, from a Chinese user point of view, because Emacs sticks to it but it does not contain the needed character.  And Emacs falling back to this font for Chinese is a long-standing bug.

P.S. Are you using a Chinese version of Windows?

Best regards,
Chris

**Comment by xvz** [comment]
Interesting. If I actually edit Chinese, it uses a mix of fonts: e.g., BatangChe, MS Gothic, MingLiu.

Anyway, I'm using an English version and don't have any Chinese language packs installed. I think BatangChe's a default font. I gave Symbola a shot but Emacs doesn't pick it up.

**Comment by zklhp** [comment]
For me the interesting points are:
1. Why Emacs think these symbols are “Chinese” (chinese-gbk)?
2. Why BatangChe is installed for English version of Windows?
3. Why Emacs uses BatangChe to display Chinese?
4. Why Emacs doesn’t pick Symbola up?

For point one, I have no idea. For point two, according to [this](https://www.microsoft.com/typography/fonts/font.aspx?FMID=1511), the font BatangChe is for Korean characters. I thought it was installed only for CJK (Chinese, Japanese, and Korean) versions. But I’m wrong. For point three, maybe it is a bug in Emacs, or maybe it is the font’s bug. I don’t know. And I have no idea how it will be changed. Is this really not present in older versions of Emacs? I doubt it. The last point is actually related to you (:grin:). Please try the following solutions:
1. Make sure the Symbola font is properly installed. Can you use it with Notepad or Emacs? Rebooting may also help.
2. If Symbola is installed, use

``` lisp
(set-fontset-font "fontset-default"
                  'symbol (font-spec :family "Symbola"))
```

or

``` lisp
(set-fontset-font "fontset-default" ?★ "Symbola")
```

Hope this helps.

**Comment by xvz** [comment]
[Wiki](https://en.wikipedia.org/wiki/List_of_typefaces_included_with_Microsoft_Windows) says it's a default font that comes with Windows. Emacs 24.5 definitely doesn't have this issue for me.

Restarting Windows got it to pick up the font properly. Interestingly, Emacs 24.5 still defaults to BatangChe, while 25.1 defaults to Symbola and... it no longer freezes :smile:.

**Comment by zklhp** [comment]
I’m glad it is fixed. Feel free to ask more questions.

**Comment by xvz** [comment]
Spoke too soon ;). Did more testing and I think it probably is [bug#24634](https://lists.gnu.org/archive/html/bug-gnu-emacs/2016-10/msg00334.html): it freezes up whenever certain fonts are present (e.g., BatangChe or MingLiu). That'd explain why it's fine in 24.5. Hopefully a future release with [the bug fix](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=44e402ead35eb9b4d0bf8a94a4d3ca933629aba9) solves this.

**Comment by momadacoding** [comment]
The issue still exists on Win10 with latest version 😢

**Comment by xvz** [comment]
Setting inhibit-compacting-font-caches to t solved it for me, though that's with Win 7.
