### ISSUE TITLE
Missing download link

### ISSUE THREAD

**Issue by jbulow** [zklhp/emacs-w64#6]
The web page says:

"Download the binary package (e.g. emacs-bin-w64-25.0.90-O2.7z)."

There is no such package or any other downloadable package on the web page or linked from github.

**Comment by zklhp** [comment]
Thank you.

I updated the page. And also add the information that there are official 64-bit versions.

P.S. That page is 2-year-old. How time flies.

**Comment by dodona2** [comment]
Ma I blind? Where is the link?

**Comment by zklhp** [comment]
I am closing the issue. Please feel free to comment.
